<div class="container">
<form action="/users" method="post">
    <legend>Faça seu Login</legend>  

    <div class="form-group">
    <small id="emailHelp" class="form-text text-muted">Enter with your username (E-mail)</small>
    <input type="text" name="email" class="form-control" >
    </div>

    <div class="form-group">
    <small id="emailHelp" class="form-text text-muted">Enter with your Password</small>
    <input type="password" name="password" class="form-control">
    </div>

    <div class="form-group">
    <input type="submit" value="Entrar" class="btn btn-primary form-control">
    </div>
    </div>
 </form>
 </div>